### PR TITLE
New implementation of progress bar

### LINKED ISSUE #212: Add an indicator when a new page is being loaded
Because we use AJAX to load each page’s content after the first page load, we don’t get all of the browser’s standard indicators that a new page is being loaded. This is particularly bad on mobile, where it might take longer to load the page, so it’s unclear whether anything is loading or not.

### PR DESCRIPTION
**Pull request by bitwhiz**
Inlcude a lightweight progress bar library that is only 1.69 KB and
implement code for monitoring progress of ajax requests.

Resolves #212

### CODE REVIEW

**Comment by Rlin415** [comment]
High speed

fast

Regular 2G

slow

@chasenlehara ^

**Comment by chasenlehara** [comment]
Cool. With the slower example, it doesn’t look like there’s any indication from the time the user clicks on a link to when it starts loading the page, which means it’s unclear whether it’s started loading. Is that the case?

**Comment by Rlin415** [comment]
Yeah, that's the case. The progress bar only shows when the client actually starts downloading the page from the server. If we want to show some progress from the time the user clicks on a link to when they actually start downloading the page, I can set some kind of arbitrary length to the bar.

**Comment by chasenlehara** [comment]
Closing in favor of https://github.com/canjs/bit-docs-html-canjs/pull/238

**Pull request closed without merging**
