### PR TITLE
Updates to On This Page CSS

### PR DESCRIPTION
**Pull request by jamiemccue**
- Refactoring the menu so the <a> has the padding and <li> is just the
wrapper
- Separating the / as an individual li
- Reversing out the background when selected
- Removing the caret triangle altogether

screen shot 2017-05-29 at 1 39 16 pm

### CODE REVIEW

**Comment by justinbmeyer** [comment]
Do we have rounded elsewhere? Not sure it fits with brutalist aethstetic.

**Comment by jamiemccue** [comment]
Removed border radius

**Comment by chasenlehara** [comment]
@imaustink Would you mind fixing that issue please?

**Comment by imaustink** [comment]
Updated PR:
image

**Comment by imaustink** [comment]
@chasenlehara I've updated the PR to address that issue.

image

image

**Pull request merged**
