### PR TITLE
CSS Updates

### PR DESCRIPTION
**Pull request by tomgreever**
Basic setup for HTML & CSS. 

Made with <3 for @justinbmeyer 

screen shot 2016-06-29 at 5 31 55 pm

### CODE REVIEW

**Comment by justinbmeyer** [comment]
localhost_8080_bit-docs-html-canjs_temp_can-component_html


merged it, but is having everything bold there a mistake?  It seems like overkill and distracts from the path that is open.

**Comment by tomgreever** [comment]
Yeah a mistake. I didn't realize 'active' would be all the siblings and parent too. Anyway there are still lots of things to tweak. I ain't done yet!

**Comment by tomgreever** [comment]
I'm not even sure bold is the roge choice but I needed something just for my own sanity while playing around

**Comment by tomgreever** [comment]
Roge. Right.

**Comment by justinbmeyer** [comment]
yeah, that's probably a bug.  I'll fix it.

**Comment by justinbmeyer** [comment]
actually, it's how the styles were applied.  I'll fix that.

**Pull request merged**
