### PR TITLE
Move the in-page nav into the main content

### PR DESCRIPTION
**Pull request by chasenlehara**
Chasen/dev tasks:

- [x] Add the TOC component
- [x] Scroll to the top of the TOC sidebar when a new page is loaded
- [ ] Polyfill for Edge

Ryan tasks:

- [x] Style it (probably bring in [these styles](https://github.com/bitovi/academy/blob/7bd0ac169869117ad92b3afaff08c25bd4ef26a9/static/styles/styles.less#L571-L695))
- [x] Make the bullets (and lines?) smaller
- [x] Bottom padding in TOC sidebar
- [x] Make a mockup of what connecting the first dots would look like [get signoff from Justin]

Need to figure out:

- [ ] Do we want to connect the dots?

Will close https://github.com/canjs/canjs/issues/4744

### CODE REVIEW

**Comment by justinbmeyer** [comment]
I don't think we need to polyfill for browsers that don't support it.  I wrote TOC in such a way it's a no-op in browsers that don't support what is needed.

I thought Edge supports some limited custom elements.  We could probably just modify to use that: https://github.com/bit-docs/bit-docs-html-toc/blob/master/safe-custom-element.js

**Comment by ryangwilson** [comment]
Mocked-up angled into nest concept
dots all gray

dots with blue

(imo I don't like it)

**Comment by ryangwilson** [comment]
Looking good on all major/current desktop browsers *except* Edge. Working on a fix for Edge (this is a layout issue, not related to the TOC/polyfill menu not showing up)

**Comment by ryangwilson** [comment]
Edge fix layout screenshots
Screen Shot 2019-05-16 at 12 14 53 PM
Screen Shot 2019-05-16 at 12 14 45 PM
Screen Shot 2019-05-16 at 12 14 36 PM
Screen Shot 2019-05-16 at 12 14 29 PM

**Comment by ryangwilson** [comment]
The change in scale for the SVG icons for the TOC sidebar work well on the community page as well 
Screen Shot 2019-05-16 at 12 29 22 PM

Question for @ – For the social links should we change the Community page order to match the TOC sidebar order? Not necessary for this PR, but something to consider.

**Comment by ryangwilson** [comment]
Angles added downwards in the nesting chain – tested on MacOS Chrome, FF, and Safari, and PC Chrome and FF. Edge doesn't work bc of known issue where TOC is not appearing
Screen Shot 2019-05-16 at 2 29 35 PM

**Comment by ryangwilson** [comment]
@chasenlehara we are having failing tests that need to be resolved (looks like master has the same issue as well). @justinbmeyer asked to put this on hold until you return. Aside from that, this branch should be ready.

**Pull request merged**
