### PR TITLE
Adding client search

### PR DESCRIPTION
**Pull request by mickmcgrath13**
This Depends on: 
* ~https://github.com/bit-docs/bit-docs-generate-html/issues/9~
* ~https://github.com/bit-docs/bit-docs-generate-html/pull/30~
* ~https://github.com/bit-docs/bit-docs-generate-html/pull/33~

### CODE REVIEW

**Comment by mickmcgrath13** [comment]
Things still to do (some may need discussion)
- [ ] - Responsive (do we want it to show up on mobile?
- [ ] - WebWorkers (it isn't immediately obvious to me how to set this up - i've never done it before)
- [ ] - fall-through-cache style caching with localStorage (compatible with web workers?)
- [ ] - general review of the code (it feels a bit nasty to me for some reason)

**Comment by mickmcgrath13** [comment]
@justinbmeyer  There is still one issue with this.  

The search result links are currently using a [`pathPrefix`](https://github.com/canjs/bit-docs-html-canjs/pull/190/files#diff-a24f5555e3306cb8aa2590affeabba0bR19) which is set, via `pathToDest` [here](https://github.com/canjs/bit-docs-html-canjs/blob/123-search/templates/layout.mustache#L53).

That `pathToDest` helper is in [bit-docs-generate-html](https://github.com/bit-docs/bit-docs-generate-html/blob/master/build/make_default_helpers.js#L329).

When `index.html` or a page at the root of the output directory `temp` is loaded, all the links point to the correct place.

The problem is that when a page is loaded from a "sub-directory" from the output directory (for example, `/temp/can-connect/base/base.algebra.html`).  The `pathToDest` helper returns something like `"../.."`.

One way to resolve this, potentially, would be to simply store the outputDirectory (maybe named differently), in this case `temp/`, on the window.

I'm not able to focus on this at the moment, but if you have a quick fix, I'd be happy to implement it within this PR.  Otherwise, I'd say let's merge this PR and create an issue for the url issue in the search.

**Comment by justinbmeyer** [comment]
Unless I'm missing something, we shouldn't merge this if its not going to work on any nested page. 

The fix is to use steal.joinURI or I think can-until has something similar

**Comment by justinbmeyer** [comment]
We should remove `pathToDest` `<script>` hack.

`pathToRoot` is already available on the `docObject` like:

cursor_and_canjs_-_joinuris


Can't we use http://v3.canjs.com/doc/can-util/js/join-uris/join-uris.html 

```js
window.location.href //-> http://localhost/apps/canjs/doc/can-util/js/join-uris/join-uris.html

currentDocObject.htmlPath //-> "can-util/js/join-uris/join-uris.html"
docObject.pathToRoot //-> "../../../.."
searchResult.htmlPath //-> "can-connect/something.html"

var root = joinURIs(currentDocObject.htmlPath, docObject.pathToRoot);
root //-> "http://localhost/apps/canjs/"
var newUrl = joinURIs(root, searchResult.htmlPath )

root //-> "http://localhost/apps/canjs/can-connect/something.html"
```

**Comment by matthewp** [comment]
Looks like this has been updated. Can you rebase with master?

**Comment by matthewp** [comment]
LGTM

**Pull request merged**
